# Generated by Django 2.1.3 on 2018-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsECNPBClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('incomingValue', models.CharField(max_length=64)),
                ('mappedValue', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Ts ecnpb client',
                'verbose_name_plural': 'Ts ecnpb clients',
                'db_table': 'ts_ecnpb_client',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsECNPBEcn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('ecnName', models.CharField(max_length=64, verbose_name='ECN NAME')),
            ],
            options={
                'db_table': 'ts_ecnpb_ecn',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsECNPBExecutingBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('incomingValue', models.CharField(max_length=64)),
                ('mappedValue', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128, verbose_name='EB Name')),
                ('fk_ecn', models.ForeignKey(on_delete=False, to='app_routemaster_ecnpb.TsECNPBEcn')),
            ],
            options={
                'db_table': 'ts_ecnpb_executingbroker',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsECNPBPrimeBroker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('pbName', models.CharField(max_length=64, verbose_name='PB NAME')),
            ],
            options={
                'db_table': 'ts_ecnpb_primebroker',
                'ordering': ['date_added'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tsecnpbprimebroker',
            unique_together={('pbName',)},
        ),
        migrations.AddField(
            model_name='tsecnpbexecutingbroker',
            name='fk_pb',
            field=models.ForeignKey(on_delete=False, to='app_routemaster_ecnpb.TsECNPBPrimeBroker'),
        ),
        migrations.AlterUniqueTogether(
            name='tsecnpbecn',
            unique_together={('ecnName',)},
        ),
        migrations.AddField(
            model_name='tsecnpbclients',
            name='fk_ecn',
            field=models.ForeignKey(on_delete=False, to='app_routemaster_ecnpb.TsECNPBEcn'),
        ),
        migrations.AddField(
            model_name='tsecnpbclients',
            name='fk_pb',
            field=models.ForeignKey(on_delete=False, to='app_routemaster_ecnpb.TsECNPBPrimeBroker'),
        ),
        migrations.AlterUniqueTogether(
            name='tsecnpbclients',
            unique_together={('name',)},
        ),
    ]
