# Generated by Django 2.1.3 on 2018-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsDeutClients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('compId', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Ts deut client',
                'verbose_name_plural': 'Ts deut clients',
                'db_table': 'ts_deut_clients',
                'ordering': ['dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='TsDeutIpRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('host_ip', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_deut.TsDeutClients')),
            ],
            options={
                'db_table': 'ts_deut_ip_rule',
                'ordering': ['host_ip'],
            },
        ),
        migrations.CreateModel(
            name='TsDeutNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_deut.TsDeutClients')),
            ],
            options={
                'db_table': 'ts_deut_note',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsDeutRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateField(auto_now_add=True)),
                ('routeId', models.CharField(max_length=64)),
                ('routingStatus', models.CharField(choices=[('relay', 'relay'), ('proxy', 'proxy'), ('both', 'both')], max_length=5, null=True)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_deut.TsDeutClients')),
            ],
            options={
                'db_table': 'ts_deut_routes',
                'ordering': ['dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='TsDeutTargetServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('targetserver_ip', models.CharField(max_length=100)),
                ('targetserver_port', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ts deut targetserver',
                'verbose_name_plural': 'Ts deut targetserver',
                'db_table': 'ts_deut_targetserver',
                'ordering': ['-date_added'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tsdeutclients',
            unique_together={('compId',)},
        ),
        migrations.AlterUniqueTogether(
            name='tsdeutroute',
            unique_together={('routeId',)},
        ),
    ]
