# Generated by Django 2.1.3 on 2018-11-14 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TsSTDClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('compId', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128, verbose_name='Client name')),
                ('client_type', models.CharField(choices=[('contributor', 'contributor'), ('consumer', 'consumer')], max_length=15, null=True)),
            ],
            options={
                'db_table': 'ts_std_clients',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDIpRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('host_ip', models.CharField(max_length=30)),
                ('comment', models.CharField(blank=True, max_length=2000, null=True)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_std.TsSTDClient')),
            ],
            options={
                'db_table': 'ts_std_ip_rule',
                'ordering': ['host_ip'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=10000, null=True)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_std.TsSTDClient')),
            ],
            options={
                'db_table': 'ts_std_note',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('permission_type', models.CharField(choices=[('cn-name', 'cn-name'), ('ip-address', 'ip-address'), ('executing-system', 'executing-system')], max_length=20, null=True)),
                ('permission_value', models.CharField(max_length=100)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_std.TsSTDClient')),
            ],
            options={
                'db_table': 'ts_std_permission',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('route_id', models.CharField(max_length=64)),
                ('fk_client', models.ForeignKey(on_delete=False, to='app_routemaster_std.TsSTDClient')),
            ],
            options={
                'db_table': 'ts_std_route',
                'ordering': ['date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDTargetServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('client_type', models.CharField(choices=[('contributor', 'contributor'), ('consumer', 'consumer')], max_length=15, null=True)),
                ('targetserver_ip', models.CharField(max_length=100)),
                ('targetserver_port', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ts_std_targetserver',
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='TsSTDVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'db_table': 'ts_std_vendor',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='tsstdvendor',
            unique_together={('name',)},
        ),
        migrations.AddField(
            model_name='tsstdroute',
            name='fk_vendor',
            field=models.ForeignKey(on_delete=False, to='app_routemaster_std.TsSTDVendor'),
        ),
        migrations.AlterUniqueTogether(
            name='tsstdclient',
            unique_together={('name', 'compId')},
        ),
        migrations.AlterUniqueTogether(
            name='tsstdroute',
            unique_together={('route_id', 'fk_vendor', 'fk_client')},
        ),
        migrations.AlterUniqueTogether(
            name='tsstdiprule',
            unique_together={('host_ip', 'fk_client')},
        ),
    ]
